// Code generated by mockery v2.17.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Allen-Career-Institute/test-and-assessment-commons/pkg/data/entity"
	mock "github.com/stretchr/testify/mock"
)

// IStudentTestInsightRepository is an autogenerated mock type for the IStudentTestInsightRepository type
type IStudentTestInsightRepository struct {
	mock.Mock
}

type IStudentTestInsightRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IStudentTestInsightRepository) EXPECT() *IStudentTestInsightRepository_Expecter {
	return &IStudentTestInsightRepository_Expecter{mock: &_m.Mock}
}

// CreateStudentTestInsight provides a mock function with given fields: ctx, studentTestInsight
func (_m *IStudentTestInsightRepository) CreateStudentTestInsight(ctx context.Context, studentTestInsight entity.StudentTestInsightEntity) error {
	ret := _m.Called(ctx, studentTestInsight)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.StudentTestInsightEntity) error); ok {
		r0 = rf(ctx, studentTestInsight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IStudentTestInsightRepository_CreateStudentTestInsight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStudentTestInsight'
type IStudentTestInsightRepository_CreateStudentTestInsight_Call struct {
	*mock.Call
}

// CreateStudentTestInsight is a helper method to define mock.On call
//   - ctx context.Context
//   - studentTestInsight entity.StudentTestInsightEntity
func (_e *IStudentTestInsightRepository_Expecter) CreateStudentTestInsight(ctx interface{}, studentTestInsight interface{}) *IStudentTestInsightRepository_CreateStudentTestInsight_Call {
	return &IStudentTestInsightRepository_CreateStudentTestInsight_Call{Call: _e.mock.On("CreateStudentTestInsight", ctx, studentTestInsight)}
}

func (_c *IStudentTestInsightRepository_CreateStudentTestInsight_Call) Run(run func(ctx context.Context, studentTestInsight entity.StudentTestInsightEntity)) *IStudentTestInsightRepository_CreateStudentTestInsight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.StudentTestInsightEntity))
	})
	return _c
}

func (_c *IStudentTestInsightRepository_CreateStudentTestInsight_Call) Return(_a0 error) *IStudentTestInsightRepository_CreateStudentTestInsight_Call {
	_c.Call.Return(_a0)
	return _c
}

// FindByStudentIDTestID provides a mock function with given fields: ctx, studentID, testID
func (_m *IStudentTestInsightRepository) FindByStudentIDTestID(ctx context.Context, studentID string, testID string) (*entity.StudentTestInsightEntity, error) {
	ret := _m.Called(ctx, studentID, testID)

	var r0 *entity.StudentTestInsightEntity
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.StudentTestInsightEntity); ok {
		r0 = rf(ctx, studentID, testID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.StudentTestInsightEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, studentID, testID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IStudentTestInsightRepository_FindByStudentIDTestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStudentIDTestID'
type IStudentTestInsightRepository_FindByStudentIDTestID_Call struct {
	*mock.Call
}

// FindByStudentIDTestID is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID string
//   - testID string
func (_e *IStudentTestInsightRepository_Expecter) FindByStudentIDTestID(ctx interface{}, studentID interface{}, testID interface{}) *IStudentTestInsightRepository_FindByStudentIDTestID_Call {
	return &IStudentTestInsightRepository_FindByStudentIDTestID_Call{Call: _e.mock.On("FindByStudentIDTestID", ctx, studentID, testID)}
}

func (_c *IStudentTestInsightRepository_FindByStudentIDTestID_Call) Run(run func(ctx context.Context, studentID string, testID string)) *IStudentTestInsightRepository_FindByStudentIDTestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IStudentTestInsightRepository_FindByStudentIDTestID_Call) Return(_a0 *entity.StudentTestInsightEntity, _a1 error) *IStudentTestInsightRepository_FindByStudentIDTestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewIStudentTestInsightRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStudentTestInsightRepository creates a new instance of IStudentTestInsightRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStudentTestInsightRepository(t mockConstructorTestingTNewIStudentTestInsightRepository) *IStudentTestInsightRepository {
	mock := &IStudentTestInsightRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
