// Code generated by mockery v2.17.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Key is an autogenerated mock type for the Key type
type Key struct {
	mock.Mock
}

type Key_Expecter struct {
	mock *mock.Mock
}

func (_m *Key) EXPECT() *Key_Expecter {
	return &Key_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewKey interface {
	mock.TestingT
	Cleanup(func())
}

// NewKey creates a new instance of Key. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKey(t mockConstructorTestingTNewKey) *Key {
	mock := &Key{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
