// Code generated by mockery v2.17.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Offset is an autogenerated mock type for the Offset type
type Offset struct {
	mock.Mock
}

type Offset_Expecter struct {
	mock *mock.Mock
}

func (_m *Offset) EXPECT() *Offset_Expecter {
	return &Offset_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewOffset interface {
	mock.TestingT
	Cleanup(func())
}

// NewOffset creates a new instance of Offset. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOffset(t mockConstructorTestingTNewOffset) *Offset {
	mock := &Offset{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
